services:
  # BD - MySQL
  mysql:
    image: mysql:8.0
    container_name: dmh-mysql
    restart: always
    environment:
      MYSQL_DATABASE: db_keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dmh-network
    command:
      - --default-authentication-plugin=mysql_native_password

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.5
    container_name: dmh-keycloak
    restart: always
    environment:
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://mysql:3306/db_keycloak?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak

      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin

      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8180

    ports:
      - "8180:8080"
    depends_on:
      - mysql
    networks:
      - dmh-network

    volumes:
      - ./keycloak-config/realm-export.json:/opt/keycloak/data/import/realm.json

    command:
      - start-dev
      - --import-realm

volumes:
  mysql_data:

networks:
  dmh-network:
    driver: bridge